/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_api_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blik_files/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_blik_files_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blik_files/statistics/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Stats */
        post: operations["refresh_stats_api_blik_files_statistics_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blik_files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Csv
         * @description Upload a CSV file and parse its contents. The file is stored temporarily for further processing.
         *      Returns an UploadResponse containing the number of records parsed and a unique file ID.
         *
         *     Args:
         *         file (UploadFile): The CSV file to be uploaded.
         *
         *     Returns:
         *         UploadResponse: Response containing message, count of records, and encoded file ID.
         */
        post: operations["upload_csv_api_blik_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blik_files/{encoded_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tempfile
         * @description Retrieve and preview the contents of an uploaded CSV file by its encoded ID.
         *
         *     Args:
         *         encoded_id (str): The base64url encoded ID of the uploaded file.
         *
         *     Returns:
         *         FilePreviewResponse: Response containing file details and parsed content.
         */
        get: operations["get_tempfile_api_blik_files__encoded_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blik_files/{encoded_id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Do Match
         * @description Process the uploaded CSV file to find matching transactions in Firefly III.
         *
         *     Args:
         *         encoded_id (str): The base64url encoded ID of the uploaded file.
         *
         *     Returns:
         *     FileMatchResponse: Response containing match results and statistics.
         */
        get: operations["do_match_api_blik_files__encoded_id__matches_get"];
        put?: never;
        /**
         * Apply Matches
         * @description Apply selected matches to the transactions in Firefly III.
         *
         *     Args:
         *         encoded_id (str): The base64url encoded ID of the uploaded file.
         *         payload (ApplyPayload): Payload containing the list of CSV indexes to apply.
         *
         *     Returns:
         *         FileApplyResponse: Response containing the number of updated transactions and any errors.
         */
        post: operations["apply_matches_api_blik_files__encoded_id__matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_system_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version Check */
        get: operations["version_check_api_system_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tx/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tx */
        get: operations["get_tx_api_tx_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tx/{tx_id}/category/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Category */
        post: operations["apply_category_api_tx__tx_id__category__category_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyPayload */
        ApplyPayload: {
            /** Tx Indexes */
            tx_indexes: number[];
        };
        /** Body_login_for_access_token_api_auth_token_post */
        Body_login_for_access_token_api_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_upload_csv_api_blik_files_post */
        Body_upload_csv_api_blik_files_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** FileApplyResponse */
        FileApplyResponse: {
            /** File Id */
            file_id: string;
            /** Updated */
            updated: number;
            /** Errors */
            errors: string[];
        };
        /** FileMatchResponse */
        FileMatchResponse: {
            /** File Id */
            file_id: string;
            /** Decoded Name */
            decoded_name: string;
            /** Records In File */
            records_in_file: number;
            /** Transactions Found */
            transactions_found: number;
            /** Transactions Not Matched */
            transactions_not_matched: number;
            /** Transactions With One Match */
            transactions_with_one_match: number;
            /** Transactions With Many Matches */
            transactions_with_many_matches: number;
            /** Content */
            content: components["schemas"]["MatchResult"][];
        };
        /** FilePreviewResponse */
        FilePreviewResponse: {
            /** File Id */
            file_id: string;
            /** Decoded Name */
            decoded_name: string;
            /** Size */
            size: number;
            /** Content */
            content: components["schemas"]["SimplifiedRecord"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Database */
            database?: string | null;
            /** External Services */
            external_services?: {
                [key: string]: string;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** MatchResult */
        MatchResult: {
            tx: components["schemas"]["SimplifiedTx"];
            /** Matches */
            matches: components["schemas"]["SimplifiedRecord"][];
        };
        /** ScreeningResponse */
        ScreeningResponse: {
            tx: components["schemas"]["SimplifiedTx"];
            /** Categories */
            categories: components["schemas"]["SimplifiedCategory"][];
        };
        /** SimplifiedCategory */
        SimplifiedCategory: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** SimplifiedRecord */
        SimplifiedRecord: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: number;
            /** Details */
            details: string;
            /** Recipient */
            recipient: string;
            /** Operation Amount */
            operation_amount: number;
            /**
             * Sender
             * @default
             */
            sender: string;
            /**
             * Operation Currency
             * @default PLN
             */
            operation_currency: string;
            /**
             * Account Currency
             * @default PLN
             */
            account_currency: string;
            /**
             * Sender Account
             * @default
             */
            sender_account: string;
            /**
             * Recipient Account
             * @default
             */
            recipient_account: string;
        };
        /** SimplifiedTx */
        SimplifiedTx: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: number;
            /** Id */
            id: string;
            /** Description */
            description: string;
            /** Tags */
            tags: string[];
            /** Notes */
            notes: string;
            /** Category */
            category: string;
        };
        /** StatisticsResponse */
        StatisticsResponse: {
            /** Total Transactions */
            total_transactions: number;
            /** Single Part Transactions */
            single_part_transactions: number;
            /** Uncategorized Transactions */
            uncategorized_transactions: number;
            /** Filtered By Description Exact */
            filtered_by_description_exact: number;
            /** Filtered By Description Partial */
            filtered_by_description_partial: number;
            /** Not Processed Transactions */
            not_processed_transactions: number;
            /** Not Processed By Month */
            not_processed_by_month: {
                [key: string]: number;
            };
            /** Inclomplete Procesed By Month */
            inclomplete_procesed_by_month: {
                [key: string]: number;
            };
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Message */
            message: string;
            /** Count */
            count: number;
            /** Id */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Version */
            version: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_for_access_token_api_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_api_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_blik_files_statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsResponse"];
                };
            };
        };
    };
    refresh_stats_api_blik_files_statistics_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsResponse"];
                };
            };
        };
    };
    upload_csv_api_blik_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_csv_api_blik_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tempfile_api_blik_files__encoded_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encoded_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    do_match_api_blik_files__encoded_id__matches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encoded_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_matches_api_blik_files__encoded_id__matches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encoded_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_system_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    version_check_api_system_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    get_tx_api_tx_next_get: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
                after_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next transaction for screening */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description No more transactions to screen */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Firefly error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apply_category_api_tx__tx_id__category__category_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tx_id: number;
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
