version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      sveltejs:
        patterns:
          - '@sveltejs/*'
      vite:
        patterns:
          - 'vite*'
      vitest:
        patterns:
          - 'vitest*'
      testing-library:
        patterns:
          - '@testing-library/*'
    commit-message:
      prefix: 'deps(ui)'
    labels:
      - dependencies
